Repository boppygames/Community-Game, pull requests merged in 2021-07, with the labels that each got.

#28 Asset patches
  .gitignore
  patch-apply.sh
  patch-create.sh
Labels: Ready for Merge

#24 Inventory Controller + Items
  Assets/Features/Inventory.meta
  Assets/Features/Inventory/InventoryController.cs
  Assets/Features/Inventory/InventoryController.cs.meta
  Assets/Features/Inventory/InventorySlot.cs
  Assets/Features/Inventory/InventorySlot.cs.meta
  Assets/Features/Inventory/Item.cs
  Assets/Features/Inventory/Item.cs.meta
  Assets/Features/Inventory/Tests.meta
  Assets/Features/Inventory/Tests/InventoryTest.cs
  Assets/Features/Inventory/Tests/InventoryTest.cs.meta
  Assets/Features/Inventory/Tests/InventoryTestScene.unity
  Assets/Features/Inventory/Tests/InventoryTestScene.unity.meta
  Assets/Features/Inventory/Tests/Non-Stackable Test Item.asset
  Assets/Features/Inventory/Tests/Non-Stackable Test Item.asset.meta
  Assets/Features/Inventory/Tests/Stackable Test Item.asset
  Assets/Features/Inventory/Tests/Stackable Test Item.asset.meta
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/TimelineSettings.asset
Labels: Ready for Merge, priority

#39 Entity and Combat
  Assets/Features/Combat/Scripts.meta
  Assets/Features/Combat/Scripts/EntityHealthController.cs
  Assets/Features/Combat/Scripts/EntityHealthController.cs.meta
  Assets/Features/Entity/EnemyController.cs
  Assets/Features/Entity/EnemyController.cs.meta
  Assets/Features/Entity/EntityController.cs
  Assets/Features/Entity/EntityController.cs.meta
  Assets/Features/Entity/PlayerController.cs
  Assets/Features/Entity/PlayerController.cs.meta
  Assets/Features/Entity/PlayerManager.cs
  Assets/Features/Entity/PlayerManager.cs.meta
Labels: priority
